### PR TITLE
modify schema

### PR DESCRIPTION
**Pull request by Tezigudo**

### CODE REVIEW

**Review by koonwill — COMMENTED** [review]
Typo in db.py is_celemonies should be is_ceremonies
And question on the is_ceremonies, and SportStatus.CEREMONIES isn't it the same?

**Comment by Tezigudo** [comment]
> Typo in db.py is_celemonies should be is_ceremonies And question on the is_ceremonies, and SportStatus.CEREMONIES isn't it the same?

Oh ok i will fix it

**Review by koonwill — CHANGES_REQUESTED** [review]
Its looking good now, but the typo is still wrong on sport_schejule_body in @app.get('/2')

**Review by koonwill — APPROVED** [review]
Goodwork

**Pull request merged**
